### ISSUE TITLE
Can't Produce Segmentation Data

### ISSUE THREAD

**Issue by skarakulak** [developmentseed/label-maker#118] opened 2018-11-08 22:54 UTC
Hi,

I was trying to produce a segmentation data on an area in Philippines with the configuration below. `label-maker download` command creates the mbtiles and geojson files. However when I try to produce the labels and images, label-maker just creates empty folders. Where do I do wrong? I have installed mbviewer and made sure that the region that I downloaded contains labels.

```
{
  "country": "philippines",
  "bounding_box": [121.464843728242,18.312810843256784,121.50878904073498,18.354525525951416],
  "zoom": 12,
  "classes": [
    { "name": "Landuse", "filter": ["has", "landuse"] },
    { "name": "Roads", "filter": ["has", "highway"] },
    { "name": "Building", "filter": ["has", "building"] }
  ],
"imagery": "http://a.tiles.mapbox.com/v4/mapbox.satellite/{z}/{x}/{y}.jpg?access_token=pk.eyJ1Ijoic2thcmFrdWxhayIsImEiOiJjam54Z3YwaDYwMGhkM3FwY3BmeG1lZHd5In0.dAFYUvWpcw7katdB9xeBSg",
  "background_ratio": 1,
  "ml_type": "segmentation"
}

```

**Comment by drewbo** [comment] 2018-11-09 16:39
@skarakulak just checked it out and I can confirm that I'm seeing the same issue. I'll mess around with this for a while and update soon. Thanks for the bug report!

**Comment by drewbo** [comment] 2018-11-09 17:54
@skarakulak Looks like there is a `TopologicalError` thrown by one of the geometries and it silently causes the tile processing section to fail. I'll add some handling for that to fix this

**Comment by skarakulak** [comment] 2018-11-09 19:00
Thanks a lot for the quick response, much appreciated

**Comment by skarakulak** [comment] 2018-11-09 20:30
I have tried with the latest code but still getting no labels:

```
serkan@serkan-HP-ubuntu:~/temp_geo$ label-maker labels
Determining labels for each tile
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 9 247 at 9 247
---
Landuse: 0 tiles
Roads: 0 tiles
Building: 0 tiles
Total tiles: 4
Writing out labels to data/labels.npz
serkan@serkan-HP-ubuntu:~/temp_geo$ label-maker images
Downloading 0 tiles to data/tiles

```

**Comment by drewbo** [comment] 2018-11-09 20:53
@skarakulak it still isn't merged in yet. If you want to try it out now, you can install directly from the repo (`pip install -e .`) on the branch `bug/118-skip-bad-geometries`. Otherwise, we'll have a new release early next week

**Closed** 2018-11-09 21:34 UTC
Labels: bug

**Comment by NickElixir** [comment] 2019-06-13 11:28
I got same problem.
```
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 226 179 at 226 179
```
Analogical errors appear with other bounding boxes.
Is this bug or my mistake?

**Comment by NickElixir** [comment] 2019-06-13 11:32
I tried the example from [devseed.com](http://devseed.com/label-maker/) and got same:
`TopologyException: Input geom 0 is invalid: Self-intersection at or near point 216 84 at 216 84
The operation 'GEOSIntersection_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.polygon.Polygon object at 0x7fe07347d898> skipping`
What's the problem?

**Comment by Geoyi** [comment] 2019-06-13 11:37
@NickElixir, check your (multi)polygon/geometry, when it was created, some bow-tie/intersect was accidentally created. Check this - [How to fix invalid polygon with self-intersection - Python ](https://gis.stackexchange.com/questions/311209/how-to-fix-invalid-polygon-with-self-intersection-python).

**Comment by NickElixir** [comment] 2019-06-13 11:55
@Geoyi, I don't understand what I should do. This is my bounding box: `[1.09725, 6.05520, 1.34582, 6.30915]`

**Comment by skarakulak** [comment] 2019-06-13 12:58
Hey Nick,
It's been a while and I don't remember how I solved that particular issue.
However I made some changes with the label-maker which worked for me in the
end. Perhaps you might wanna go through the commits here
https://github.com/skarakulak/label-maker

Also you can clone the fork and try to get the data with your bounding box
with this modified version. My solution was kind of a quick hack, and it
changed the default behavior of label-maker which might result in undesired
behavior in other tasks other than segmentation. So I didn't open a PR for
it.

Sorry for not being more helpful. Let me know if this doesn't solve the
problem or if you have any questions regarding the changes that I have made
in the fork.

Best,
Serkan

**Comment by NickElixir** [comment] 2019-06-13 13:15
@skarakulak I use Colab for downloading images for segmentation. How I can install your fork in Colab?

**Comment by drewbo** [comment] 2019-06-13 18:13
@NickElixir @skarakulak @Geoyi the problematic geometries sometimes come directly from OSM or when they get chopped up by our tiling. It will show the warning but skips the geometry and should continue from there.

@NickElixir are you still getting results after seeing that warning?

**Comment by NickElixir** [comment] 2019-06-13 19:04
I got some but less now. Does this error mean that I skip tags?
I see that dataset is not full and not balanced.

**Comment by drewbo** [comment] 2019-06-14 12:55
@NickElixir it's possible to fix the underlying geometries first then load as a GeoJSON but that's a bit of a pain. When you say that you're getting "less now" (I assume labels), less than when?
